sudo: required
services:
  - docker

before_install:
  - docker build -t iamkumaranca/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run iamkumaranca/react-test npm test -- --coverage

after_success:
  - docker build -t iamkumaranca/multi-client ./client
  - docker build -t iamkumaranca/multi-nginx ./nginx
  - docker build -t iamkumaranca/multi-server ./server
  - docker build -t iamkumaranca/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push iamkumaranca/multi-client
  - docker push iamkumaranca/multi-nginx
  - docker push iamkumaranca/multi-server
  - docker push iamkumaranca/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker-course 
  env: MultiDockerCourse-env
  bucket_name: elasticbeanstalk-ca-central-1-392102108912
  bucket_path: docker-multi-course
  on:
      branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY